name: health-wrapped
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastapi==0.115.6
    - uvicorn==0.34.0
    - python-multipart==0.0.20
    - pydantic==2.10.4
